export const jinisoYouthData = [
  {
    id: 1,
    name: "JINISO - Highwaist Baggy Jeans GET LOW",
    image: "/PRODUCTS/JINISO - Highwaist Baggy Jeans 504 GET LOW 1.webp",
    currentPrice: "Rp 209.500,00",
    originalPrice: "Rp 627.143,00",
    discount: "58%",
    rating: 4.5,
    reviews: 30,
    isWishlist: false,
  },
  {
    id: 2,
    name: "JINISO - Highwaist Oversize Baggy Loose Jeans WEEKEND",
    image:
      "/PRODUCTS/JINISO - Highwaist Oversize Baggy Loose Jeans 770 WEEKEND 1.jpg",
    currentPrice: "Rp 219.500,00",
    originalPrice: "Rp 555.714,00",
    discount: "66%",
    rating: 4.5,
    reviews: 30,
    isWishlist: false,
  },
  {
    id: 3,
    name: "JINISO - Jaket Jeans Oversize Dalma Khaki",
    image: "/PRODUCTS/JINISO Jaket Jeans Oversize Dalma Khaki 1.webp",
    currentPrice: "Rp 205.500,00",
    originalPrice: "Rp 633.333,00",
    discount: "67%",
    rating: 4.5,
    reviews: 30,
    isWishlist: false,
  },
  {
    id: 4,
    name: "JINISO - Highwaist Loose Jeans HANGOVER",
    image: "/PRODUCTS/JINISO - Highwaist Loose Jeans 815 HANGOVER 1.webp",
    currentPrice: "Rp 180.000,00",
    originalPrice: "Rp 598.571,00",
    discount: "58%",
    rating: 4.5,
    reviews: 30,
    isWishlist: false,
  },
  {
    id: 5,
    name: "JINISO - HW Boyfriend Jeans SLAYING BABE",
    image: "/PRODUCTS/JINISO - HW Boyfriend Jeans 704 SLAYING BABE 1.jpg",
    currentPrice: "Rp 198.500,00",
    originalPrice: "Rp 598.571,00",
    discount: "68%",
    rating: 4.5,
    reviews: 30,
    isWishlist: false,
  },
];

export const jinisoStreetData = [
  {
    id: 1,
    name: "JINISO - Oversize Baggy Loose Jeans PHO",
    image: "/PRODUCTS/JINISO Oversize Baggy Loose Jeans Pria 772 1.webp",
    currentPrice: "Rp 219.500,00",
    originalPrice: "Rp 555.714,00",
    discount: "66%",
    rating: 4.5,
    reviews: 30,
    isWishlist: false,
  },
  {
    id: 2,
    name: "JINISO - Jumpsuit Overall Celana Jeans Panjang",
    image: "/api/placeholder/300/400",
    currentPrice: "Rp 199.500,00",
    originalPrice: "Rp 598.571,0",
    discount: "66%",
    rating: 4.5,
    reviews: 30,
    isWishlist: false,
  },
  {
    id: 3,
    name: "JINISO - Garis Highwaist Loose Jeans LEVEL UP",
    image: "/api/placeholder/300/400",
    currentPrice: "Rp 209.500,00",
    originalPrice: "Rp 627.143,00",
    discount: "65%",
    rating: 4.5,
    reviews: 30,
    isWishlist: false,
  },
  {
    id: 4,
    name: "JINISO - Highwaist Baggy Ripped Jeans MYSTIC GAL",
    image: "/api/placeholder/300/400",
    currentPrice: "Rp 209.500,00",
    originalPrice: "Rp 627.143,00",
    discount: "66%",
    rating: 4.5,
    reviews: 30,
    isWishlist: false,
  },
  {
    id: 5,
    name: "JINISO - Highwaist Jeans BODY GOAL",
    image: "/api/placeholder/300/400",
    currentPrice: "Rp 199.500,00",
    originalPrice: "Rp 598.571,0",
    discount: "66%",
    rating: 4.5,
    reviews: 30,
    isWishlist: false,
  },
];

export const jinisoDenimData = [
  {
    id: 1,
    name: "JINISO - HW Cutbroy Jeans HOTTY GANG",
    image: "/api/placeholder/300/400",
    currentPrice: "Rp 199.500,00",
    originalPrice: "Rp 598.571,00",
    discount: "68%",
    rating: 4.5,
    reviews: 30,
    isWishlist: false,
  },
  {
    id: 2,
    name: "JINISO - Loose Cargo Denim Jeans PHO",
    image: "/api/placeholder/300/400",
    currentPrice: "Rp 209.500,00",
    originalPrice: "Rp 633.143,00",
    discount: "67%",
    rating: 4.5,
    reviews: 30,
    isWishlist: false,
  },
  {
    id: 3,
    name: "JINISO - Highwaist Boyfriend Jeans FEEL GOOD",
    image: "/api/placeholder/300/400",
    currentPrice: "Rp 199.500,00",
    originalPrice: "Rp 598.571,0",
    discount: "56%",
    rating: 4.5,
    reviews: 30,
    isWishlist: false,
  },
  {
    id: 4,
    name: "JINISO - Highwaist Cargo Loose Jeans HANDS UP",
    image: "/api/placeholder/300/400",
    currentPrice: "Rp 201.500,00",
    originalPrice: "Rp 627.143,00",
    discount: "67%",
    rating: 4.5,
    reviews: 30,
    isWishlist: false,
  },
  {
    id: 5,
    name: "JINISO - Highwaist Rok Slit Jeans Panjang SEVENTY",
    image: "/api/placeholder/300/400",
    currentPrice: "Rp 199.500,00",
    originalPrice: "Rp 598.571,00",
    discount: "66%",
    rating: 4.5,
    reviews: 30,
    isWishlist: false,
  },
];
